### ISSUE TITLE
example script

### ISSUE THREAD

**Issue by alexander-newton** [best-practice-and-impact/gptables#16]
- [ ] iris dataset

this should take in the iris dataset in the csv and it should output something that looks very similar to the iris.xlsx that is in the example_data repo. I've already put the iris.py there with some indication of what i expect the structure and the api of the programme to look like - but obviously if you see something easier or more general then just implement it.

**Comment by foster999** [comment]
Looks good to me overall, though a few of points for discussion:

- the units arg for GPTable currently takes a str or dict. Dict is used as you've implemented here, str can be used to indicate that the same units are used for all cols.
- the index arg currently takes a dict, so that the user can specify the index level of each column (1 to 3). This allows separate formatting to be defined for each level
- it might be easiest to allow the user to specify formatting manually in rich strings, so that we don't have to detect the $$ notation or similar. I'm thinking: `title = ["This is the ", {"bold":True}, "TITLE"]`
This can then be parsed into Format objects and inserted before passing it to the `write_rich_strings()` method.
- I'm not sure if we should support the additional formatting of GPTable objects. Enforcing the use of a Theme for formatting would keep the formatting consistent across a workbook. Theme and GPTable objects are mutable, but keep the data and formatting separate until they're passed to the API method

**Comment by foster999** [comment]
Also, what are we expecting `gpt.produce_workbook()` to return?

If it is to write a file or produce a Workbook, then file and sheet names are required. We might want to take a dict of sheet names to GPTable objects to write an entire workbook?

**Comment by alexander-newton** [comment]
> Looks good to me overall, though a few of points for discussion:
> 
> * the units arg for GPTable currently takes a str or dict. Dict is used as you've implemented here, str can be used to indicate that the same units are used for all cols.

Great, I'll change.

> * the index arg currently takes a dict, so that the user can specify the index level of each column (1 to 3). This allows separate formatting to be defined for each level

Makes sense, I've changed.

> * it might be easiest to allow the user to specify formatting manually in rich strings, so that we don't have to detect the $$ notation or similar. I'm thinking: `title = ["This is the ", {"bold":True}, "TITLE"]`
>   This can then be parsed into Format objects and inserted before passing it to the `write_rich_strings()` method.

This makes sense. So how are we going to do notes? We need some manner by which we can tag notes in the text and match them to the note in the `notes` dict.

> * I'm not sure if we should support the additional formatting of GPTable objects. Enforcing the use of a Theme for formatting would keep the formatting consistent across a workbook. Theme and GPTable objects are mutable, but keep the data and formatting separate until they're passed to the API method

Is this where we just add additional formatting on the `GPWorksheet` object?
We need some way to add additional formatting.
This can't be done in `xlsxwriter` - so we need some additional memory/hierarchy object.
Taking inspiration from `xlsxpandasformatter` I want a way to apply formatting to individual rows, columns and cells. 
What do you think is the best implementation here?

**Comment by foster999** [comment]
> This makes sense. So how are we going to do notes? We need some manner by which we can tag notes in the text and match them to the note in the notes dict.

Is there a benefit from referencing the note number over the current `["Text", {'font_script': 1}, "1"]`?

The main concern is possibly ensuring that it references the correct note. But if the note changes position in the list of notes, it would still need updating manually to $$note2$$.

Ideally we'd link the reference to the text directly, so that it validates that the text exists as a note (i.e. creates it) and has the correct number. This would be harder to implement and might require the user to repeat the note text for each reference to it, if multiple. Any thoughts?


> Is this where we just add additional formatting on the GPWorksheet object? We need some way to add additional formatting. This can't be done in xlsxwriter - so we need some additional memory/hierarchy object. Taking inspiration from xlsxpandasformatter I want a way to apply formatting to individual rows, columns and cells. What do you think is the best implementation here?

Very good point. I reckon we can support this on the GPTable object then, for the table/data specifically. Other elements should be handled in the Theme, as they're just text in single cells.
We should probably support formatting for:

- entire row (inc index)
- data row (exc index)
- entire column (inc headings)
- data column (exc headings)
- cell

We should support referecing by relative position within table and by index/heading labels. Similar to pandas iloc and loc.

**Comment by alexander-newton** [comment]
>
> Is there a benefit from referencing the note number over the current `["Text", {'font_script': 1}, "1"]`?
> 
> The main concern is possibly ensuring that it references the correct note. But if the note changes position in the list of notes, it would still need updating manually to $$note2$$.
> 
> Ideally we'd link the reference to the text directly, so that it validates that the text exists as a note (i.e. creates it) and has the correct number. This would be harder to implement and might require the user to repeat the note text for each reference to it, if multiple. Any thoughts?

So my theory was that $note1$ or other \tag{} would be written in the text. Then we have a `dict` that is 
```
notes = {"note1":"This is a note.",
        "funeral":"This is also a note."}
```
and a method that is automatically called looks through all the text, arranges notes in the order that they are referenced in text (left to right top to bottom), and transforms the tag into a superscript numeral.

Basically how LaTeX works.


> 
> Very good point. I reckon we can support this on the GPTable object then, for the table/data specifically. Other elements should be handled in the Theme, as they're just text in single cells.
> We should probably support formatting for:
> 
>     * entire row (inc index)
> 
>     * data row (exc index)
> 
>     * entire column (inc headings)
> 
>     * data column (exc headings)
> 
>     * cell
> 
> 
> We should support referecing by relative position within table and by index/heading labels. Similar to pandas iloc and loc.

OK great. Are you sure this is best placed in GPTable rather than GPWorksheet?

**Comment by foster999** [comment]
The notes dict sounds great


> OK great. Are you sure this is best placed in GPTable rather than GPWorksheet?

We could do either, but if we want to reference data cells by GPTable columns or index then it might make more sense to keep it associated with the table? Plus the GPTable is acting as our fully mutable intermediate before the Worksheet - once things are added to the standard Worksheet they can only be overwritten.

**Comment by alexander-newton** [comment]
OK cool, let's put it for `GPTable` and open up some feature issues - thanks David.
